apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-vault
spec:
  provider:
    onepasswordSDK:
      vault: Homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-creds
          key: OnePToken
          namespace: external-secrets
