apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-cnpg-v1
spec:
  description: Postgres cluster for Linkding application
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  instances: 3

  storage:
    size: 1Gi
