apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-configmap
data:
  LD_DB_ENGINE: postgres
  LD_DB_DATABASE: app
  LD_DB_PORT: "5432"
  LD_DB_HOST: linkding-db-cnpg-v1-rw.linkding.svc.cluster.local
