apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/staging"
  prune: true
  timeout: 1m
  retryInterval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
