apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./monitoring/controllers/staging"
  prune: true
  timeout: 1m
  retryInterval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  
  # Health Checks for Loki and Promtail
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: loki
      namespace: monitoring
    - apiVersion: apps/v1
      kind: DaemonSet
      name: promtail
      namespace: monitoring

  # Wait for resources to be ready
  wait: true
  
---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-configs 
#  namespace: flux-system
#spec:
#  interval: 1h
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: "./monitoring/configs/staging"
#  prune: true
#  timeout: 1m
#  retryInterval: 1m
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
