apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./monitoring/controllers/staging"
  prune: true
  timeout: 1m
  retryInterval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-configs 
#  namespace: flux-system
#spec:
#  interval: 1h
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: "./monitoring/configs/staging"
#  prune: true
#  timeout: 1m
#  retryInterval: 1m
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
