apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-decrypt
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./monitoring/controllers/staging/kube-prometheus-stack"
  prune: true
  wait: true
  timeout: 1m
  retryInterval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
