apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-db-cnpg-v1
spec:
  description: Postgres cluster for Gitea application
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  instances: 3

  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi

