apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-cronjob
  namespace: renovate
spec:
  schedule: "48 */12 * * *" # At minute 48 past every 12th hour
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - cyberwatchdoug/homelab
              
              envFrom:
                - secretRef:
                    name: renovate-container-env
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never