apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-container-env
  namespace: renovate
spec:
  refreshInterval: 22h
  secretStoreRef:
    name: onepassword-vault
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: "Renovate k3s Github Token/password"
